FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev
COPY . .
RUN npm run build

# stage 2 
FROM nginx:alpine
## copy built files from stage 1
COPY --from=build /app/build  /usr/share/nginx/html
EXPOSE 80
CMD [ "nginx", "-g", "daemon off;"]